### ISSUE TITLE
zipkinの使用するelastic-searchのindexにデータが存在するにも関わらず、 zipkinでall条件で表示しても一部のデータしか表示されない

### ISSUE THREAD

**Issue by miuramiura3030** [making/zipkin-boshrelease#27]
何か該当する情報があれば共有頂けますでしょうか。
それぞれのバージョンは以下となります。
 
$ bosh releases

zipkin                              0.4.5*             
openjdk                             8.0.4*             
bpm                                 1.1.1*             
elasticsearch                       0.22.0*            
kibana                              0.15.0*            
nginx-offline-buildpack             1.0.15*

**Comment by making** [comment]
manifestももらえますか？

この事象は
* インストール後から同じ状態ですか？
* 同じバージョンを使い続けていてあるタイミングで起きましたか？
* 前のバージョンで動いていて、バージョンアップ後に起きましたか？

**Comment by miuramiura3030** [comment]
ご返答いただきありがとうございます。

>manifestももらえますか？

manifestを出力して、一番下に貼り付けました。

>・インストール後から同じ状態ですか？

9/4に環境構築し、特にその後構成は変更していません。

>・同じバージョンを使い続けていてあるタイミングで起きましたか？

・9/5に何度か試験でリクエストを発行して検索も動作する事を確認
・9/6に確認した所、9/6分の新しいリクエストについて検索表示されない状態を確認
  (9/5に試験していたリクエストは検索表示される)

>・前のバージョンで動いていて、バージョンアップ後に起きましたか？


バージョンアップは実施していません。

補足として、9/9の本日時点で確認すると、zipkinのUI topに以下エラーが表示され、
検索で9/5の過去分の検索も表示されない状態になっています。
ERROR: cannot load span names: server error (error)
ERROR: cannot load service names: server error (error)

```
# bosh -d zipkin manifest
Using environment '10.0.16.37' as client 'ops_manager'

Using deployment 'zipkin'

instance_groups:
- azs:
  - ap-northeast-1a
  - ap-northeast-1c
  - ap-northeast-1d
  instances: 3
  jobs:
  - name: java
    release: openjdk
  - consumes:
      elasticsearch:
        from: elasticsearch-master
    name: elasticsearch
    properties:
      elasticsearch:
        node:
          allow_data: true
          allow_master: true
    provides:
      elasticsearch:
        as: elasticsearch-master
    release: elasticsearch
  name: elasticsearch-master
  networks:
  - name: dev-pcf-sub-bos
  persistent_disk_type: 102400
  stemcell: xenial
  update:
    max_in_flight: 1
    serial: true
  vm_type: m5.large
- azs:
  - ap-northeast-1a
  - ap-northeast-1c
  - ap-northeast-1d
  instances: 2
  jobs:
  - name: bpm
    release: bpm
  - name: java
    release: openjdk
  - name: zipkin
    properties:
      zipkin:
        heap_size: 386m
        server_port: 9411
        storage_type: elasticsearch
    release: zipkin
  name: zipkin
  networks:
  - name: dev-pcf-sub-bos
  stemcell: xenial
  vm_extensions:
  - dev-pcf-tgt-zip
  vm_type: t3.medium
name: zipkin
releases:
- name: zipkin
  sha1: 1cf6c5bc77a583606e9b831e64f347b3f94c6373
  url: https://github.com/making/zipkin-boshrelease/releases/download/0.4.5/zipkin-boshrelease-0.4.5.tgz
  version: 0.4.5
- name: openjdk
  sha1: 43979a6595282fcf4ac6269135968acc0d96d297
  url: https://github.com/making/openjdk-boshrelease/releases/download/8.0.4/openjdk-boshrelease-8.0.4.tgz
  version: 8.0.4
- name: bpm
  sha1: 41df19697d6a69d2552bc2c132928157fa91abe0
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.4
  version: 1.0.4
- name: elasticsearch
  sha1: 959b54bc551fd910bcf77e8c1c590aad4e3cf7ec
  url: https://github.com/bosh-elastic-stack/elasticsearch-boshrelease/releases/download/0.19.0/elasticsearch-boshrelease-0.19.0.tgz
  version: 0.19.0
stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest
update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 3
  update_watch_time: 5000-600000

Succeeded
```
